import { PageHeader } from "@/components/page-header";

export default function AboutPage() {
  return (
    <article className="animate-fade-in">
      <PageHeader
        eyebrow="About"
        title="What this is,"
        emphasis="and what it isn't"
      />

      <div className="prose-stone space-y-4 text-stone-300 leading-relaxed">
        <p>
          Catalyst is a research tool for retail swing traders — built for the people
          who hold positions for a week to six months around identifiable events.
          It's not a real-time price tracker. It's not a robo-advisor. It's not a
          signal-selling service.
        </p>
        <p>
          For each upcoming catalyst, we surface five signals layered on top of the date:
          <em className="text-italic-display"> multi-catalyst stacking</em> (does this stock have
          multiple events in the window),
          <em className="text-italic-display"> options flow</em> (what the market is pricing),
          <em className="text-italic-display"> sympathy plays</em> (which peers will move),
          <em className="text-italic-display"> guidance trajectory</em> (momentum), and
          <em className="text-italic-display"> market-cap class</em> (volatility multiplier).
        </p>

        <h2 className="text-display text-2xl text-stone-100">Methodology</h2>
        <p>
          Dates come from structured sources — Financial Modeling Prep for earnings, the
          FDA OpenFDA / BioPharmCatalyst feeds for PDUFA decisions, and direct investor
          relations pages for contract awards and product events. We never source catalyst
          dates from an LLM's training data.
        </p>
        <p>
          The bull and bear theses are generated by Claude on top of the structured data
          (10-Q/10-K context where available) and validated against a schema before being
          published. Sympathy tickers are also Claude-generated, then reviewed.
        </p>

        <h2 className="text-display text-2xl text-stone-100">What we don't do</h2>
        <ul className="ml-6 list-disc space-y-1.5 text-stone-300">
          <li>We don't issue buy or sell calls.</li>
          <li>We don't connect to your broker.</li>
          <li>We don't display the monetary value of your portfolio.</li>
          <li>We don't push notifications about price moves — only about catalysts.</li>
        </ul>

        <p className="text-xs text-stone-500">
          Nothing on this site is investment advice. Past outcomes are not predictive of future
          ones. Do your own research; check sources; size positions to losses you can afford.
        </p>
      </div>
    </article>
  );
}
